services:
  server:
    build: .
    restart: always
    ports:
    - "8080:80"
  
  database:
    image: mongo
    restart: always
    ports:
    - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: sammy
      MONGO_INITDB_ROOT_PASSWORD: your_password
